apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: my-web-app-monitor
  labels:
    app: my-web-app
spec:
  selector:
    matchLabels:
      app: my-web-app
  endpoints:
  - port: web
    path: /metrics
    interval: 30s

